apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: GitRepository
metadata:
  name: admin-repository
  namespace: flux-system
spec:
  interval: 30s
  ref:
    branch: master
  url: {{.Values.repositoryUrl}}
  secretRef:
    name: git-credentials