apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: team1
  namespace: flux-system
spec:
  interval: 5m
  path: "./teams/team1/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: operations-repository