apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: root
  namespace: flux-system
spec:
  interval: 5m
  path: "./clusters/{{.Values.environment}}"
  prune: true
  sourceRef:
    kind: GitRepository
    name: admin-repository